/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Models.Usuario;

/**
 *
 * @author wilal
 */
public class JFMenu extends javax.swing.JFrame {

    Usuario user;
    
    public JFMenu() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        
    }
    
    public JFMenu(Usuario user){
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
        this.user=user;
        
        if (user.getTipo_usuario() == 1) {
            
        }else if(user.getTipo_usuario() == 2){
            menuRegistrarProductoBase.setVisible(false);
            MenuRegistrarUsuarios.setVisible(false);
            menuAdministracionUsuarios.setVisible(false);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuAdministracionBodega = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        MenuIngresoProductos = new javax.swing.JMenuItem();
        MenuSalidaProductos = new javax.swing.JMenuItem();
        menuProductosBase = new javax.swing.JMenuItem();
        menuAdministracionUsuarios = new javax.swing.JMenu();
        MenuRegistrarUsuarios = new javax.swing.JMenuItem();
        menuRegistrarProductoBase = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuAdministracionBodega.setText("Administracion de bodega");

        jMenuItem1.setText("Inventario");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuAdministracionBodega.add(jMenuItem1);

        MenuIngresoProductos.setText("Ingreso de Productos");
        MenuIngresoProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuIngresoProductosActionPerformed(evt);
            }
        });
        menuAdministracionBodega.add(MenuIngresoProductos);

        MenuSalidaProductos.setText("Salida de Productos");
        MenuSalidaProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSalidaProductosActionPerformed(evt);
            }
        });
        menuAdministracionBodega.add(MenuSalidaProductos);

        menuProductosBase.setText("Productos Base");
        menuProductosBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductosBaseActionPerformed(evt);
            }
        });
        menuAdministracionBodega.add(menuProductosBase);

        jMenuBar1.add(menuAdministracionBodega);

        menuAdministracionUsuarios.setText("Administracion de Usuarios");

        MenuRegistrarUsuarios.setText("Registrar nuevos usuarios");
        MenuRegistrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRegistrarUsuariosActionPerformed(evt);
            }
        });
        menuAdministracionUsuarios.add(MenuRegistrarUsuarios);

        menuRegistrarProductoBase.setText("Registrar Nuevos Productos Base");
        menuRegistrarProductoBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistrarProductoBaseActionPerformed(evt);
            }
        });
        menuAdministracionUsuarios.add(menuRegistrarProductoBase);

        jMenuBar1.add(menuAdministracionUsuarios);

        jMenu2.setText("Exit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JFInventario inventario = new JFInventario();
        inventario.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MenuIngresoProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuIngresoProductosActionPerformed
        JFIngresoProductos ingresoProductos = new JFIngresoProductos();
        ingresoProductos.setVisible(true);
        dispose();
    }//GEN-LAST:event_MenuIngresoProductosActionPerformed

    private void MenuSalidaProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSalidaProductosActionPerformed
        JFSalidaProductos salidaProductos = new JFSalidaProductos();
        salidaProductos.setVisible(true);
        dispose();
    }//GEN-LAST:event_MenuSalidaProductosActionPerformed

    private void menuProductosBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductosBaseActionPerformed
        JFProductosBase productosBase = new JFProductosBase();
        productosBase.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuProductosBaseActionPerformed

    private void MenuRegistrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRegistrarUsuariosActionPerformed
        JFRegistroUsuario registrarUsuarios = new JFRegistroUsuario();
        registrarUsuarios.setVisible(true);
        dispose();
    }//GEN-LAST:event_MenuRegistrarUsuariosActionPerformed

    private void menuRegistrarProductoBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistrarProductoBaseActionPerformed
        JFRegistrarProductosBase ingresoProductosBase = new JFRegistrarProductosBase();
        ingresoProductosBase.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuRegistrarProductoBaseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuIngresoProductos;
    private javax.swing.JMenuItem MenuRegistrarUsuarios;
    private javax.swing.JMenuItem MenuSalidaProductos;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menuAdministracionBodega;
    private javax.swing.JMenu menuAdministracionUsuarios;
    private javax.swing.JMenuItem menuProductosBase;
    private javax.swing.JMenuItem menuRegistrarProductoBase;
    // End of variables declaration//GEN-END:variables
}
